<KEYWORD let>
<IDENTIFIER Name>
<OPERATOR =>
<STRING 'Dulina Perera'>
<KEYWORD in>
<IDENTIFIER Print>
<PUNCTUATION (>
<STRING 'Hello '>
<PUNCTUATION ,>
<IDENTIFIER Name>
<PUNCTUATION ,>
<STRING '!'>
<PUNCTUATION )>
